### ISSUE TITLE
Add "Patch Version" field to Log__c

### ISSUE THREAD

**Issue by jamessimone** [jongpie/NebulaLogger#102]
It would be great (even as a toggleable option) to include a remote site setting for trust.salesforce.com so that the patch version the org is currently on within the Log object itself.

The format for the callout is: `https://api.status.salesforce.com/v1/instances/{sfInstanceHere}/status`

**Comment by jongpie** [comment]
I've got a basic prototype working for this, and I really like having these 2 new fields

![image](https://user-images.githubusercontent.com/1267157/111020800-3ea3b980-837d-11eb-89a1-87e8553dbe15.png)

One issue with the prototype that I want to improve: you can't make a callout directly from triggers, so I currently have a `@future` private method in `LogEntryEventHandler` making an async callout, which then updates the `Log__c` record. It won't cause issues for the current transaction (since it's all async), but I hate future methods, and it could lead to a lot of callouts if there are a lot of new logs created in an org.

I don't want to rely on platform cache (yet), so I'm thinking a workaround could be...
- Keep the `@future` private method as-is in `LogEntryEventHandler`
- Before calling the future method, first query recent `Log__c` records (created in the last hour? last day?) to see if any other records already have the new 'Release Version' and 'Release Number' fields set. If a matching log is found, just copy the field values (no callout).
- If no recent `Log__c` records have the new fields set, then use the future method to make the callout

It's not quite my favorite approach, but it would at least reduce the number of callouts made in a given timeframe (instead of making a callout for every `Log__c` record)

**Comment by jamessimone** [comment]
@jongpie I think adding in the release version/number in batches (as you've said) is a great approach, and will significantly cut down on the number of callouts made. While I have no love for future methods, since there's no state to pass into the method performing the callout, here it makes sense instead of doing something heavier like a queueable.
