### ISSUE TITLE
Start Time Issue

### ISSUE THREAD

**Issue by CloudJedi** [jongpie/NebulaLogger#162]
I'm having issues with the Start Time on the Log record.

The value on the Start Time is 6/3/2021 5:55 PM
Salesforce's Created Date: 6/3/2021 2:55 PM

The timezone on both the user and org level is "(GMT-04:00) Eastern Daylight Time (America/New_York)"

Is there a setting that I need to change to make sure it matches up?

**Comment by jongpie** [comment]
Hey @CloudJedi! Are you using multiple time zones in your org? If so, then it's potentially the same issue as #132 - that bug has been patched in the unlocked package and unpackaged metadata, but I still need to release a new version of the managed package with that fix + other recent changes.

**Comment by jongpie** [comment]
Hey @CloudJedi! Since the user and org level have the same time zone, I'm not 100% sure what the issue could be - could you try running the query below in your org and verify that the Automated Process also has the same time zone? This is the user that processes & transforms the `LogEntryEvent__e` platform events into `Log__c` and `LogEntry__c` records

- `SELECT Id, Name, TimeZoneSidKey FROM User WHERE Name = 'Automated Process'`

**Comment by CloudJedi** [comment]
@jongpie 

I just checked and the timezone is "America/Los_Angeles". Looks like this is the issue. I'm not sure where to change the timezone of this user though. I'll try to keep searching.

**Comment by jongpie** [comment]
@CloudJedi ok, then I think that explains it - it sounds like this is same issue as #132. The bug has been fixed in the (new) unlocked package, but I have not published a new version of the managed package yet. I'm hoping to do that next week, and it'll include a bugfix for this issue.

**Comment by CloudJedi** [comment]
Great thank you!

**Comment by jongpie** [comment]
@CloudJedi I've finally released v4.5.0, which includes a bugfix for this issue - you can install the latest managed package version [with this link](https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5Y0000027FMhQAM)
