### ISSUE TITLE
Is Epoch Sorting available in Logger Console?

### ISSUE THREAD

**Issue by starkguerraj** [jongpie/NebulaLogger#178]
When using Logger Console the Timestamp column for the LogEntry most times is not helpful since it displays limited precision, is there a way to add precision to this, if not is there a way to add the Epoch for sorting?

I have found sometimes that my log entries are not in the correct order and navigating to the record to compare epochs is frustrating and time consuming.

Thanks

![image](https://user-images.githubusercontent.com/72459978/128388790-4e323fdf-fd45-45a8-b895-89c3882c2da0.png)

![image](https://user-images.githubusercontent.com/72459978/128388703-abec9951-e8e5-4a33-9eca-2ff8a7c5be60.png)

**Comment by jongpie** [comment]
Hey @starkguerraj - yeah, it's a simple enough change to just include the `Epoch Timestamp` in the "All" list view on `LogEntry__c` (see screenshot below). I'll include this change in my open PR #173 - I'm hoping to finish that PR this week & I'll release new package versions for both the unlocked and managed packages.

![image](https://user-images.githubusercontent.com/1267157/128400250-8f26c4db-7a88-486f-a6d4-4130802b8865.png)

**Comment by starkguerraj** [comment]
That would be much appreciated.

Will that also cause it to appear in the LogEntry viewer of the Logs? If its something I can do without requiring a package update I can take care of it.

![image](https://user-images.githubusercontent.com/72459978/128414018-d2ee4f5f-90fb-4510-84fa-c378737dc69c.png)


Thanks.

**Comment by jongpie** [comment]
You can try editing the page layout for `Log__c` to control that - I'm not 100% sure if you can edit it (since it's part of the package), but you can test it out by going to `Setup --> Object Manager --> Log__c object --> Page Layouts`. If it lets you edit the layout, then you just have to add the Epoch Timestamp field to the `LogEntry__c` related list. If that doesn't work, let me know, but I might go ahead and include that layout change in the next package version.

**Comment by starkguerraj** [comment]
Terrific. That did the trick, thanks so much. 

I'm using the unlocked package version so I'm not sure if that made a difference in my ability to edit but it resolved my issue, Its definitely helpful at least to me to see more precision, to know that its sorted the right way.

![image](https://user-images.githubusercontent.com/72459978/128416666-3ce77eae-2505-412b-a208-9d2c1886fcd2.png)

**Comment by jongpie** [comment]
Excellent, glad to hear that worked for you! I do agree with you that having the Epoch Timestamp is nice for sorting, so I'll do some testing this evening to decide for sure if I'll include this in the next release.

**Comment by starkguerraj** [comment]
Definitely, I think in an ideal world (for me), the timestamp column would have the precision to the second/millisecond included (if that was possible) but the epoch works just fine for my use case.

Thanks for the quick responses.

**Comment by jongpie** [comment]
I'll look into ways to possibly display the Timestamp value with more precision with a formula field, but the tricky part is getting it to also display in the current user's time zone (instead of GMT). If I can't make that work, I'll include the Epoch Timestamp in the related list

**Comment by jongpie** [comment]
@starkguerraj I took another look at this just now - a better option is to use the field `LogEntry__c.TransactionEntryNumber__c` on the related list (see screenshot below). This field is automatically set to be the sequential number of each log entry within the transaction - sorting by this field on the related list will display the log entries in the exact order that they were created. Epoch timestamp should provide the same sorting, but I had created 'Transaction Entry Number' field specifically for this purpose, I just forgot to put it on the related list in a previous release :fearful: 

So, in the next release (to be released in the next few days), I'm going to include these changes:

- `LogEntry__c` list view: the "All" list view will include the `EpochTimestamp__c` field (in addition to `Timestamp__c`) so you can accurately sort all log entries
- `Log__c` page layout (shown in screenshot below): the `LogEntry__c` related list on `Log__c` will now have the `TransactionEntryNumber__c` instead of `Timestamp__c`. The related list will also sort by `TransactionEntryNumber__c` by default.

![image](https://user-images.githubusercontent.com/1267157/128436788-07662f7f-282c-4d95-a282-3cdaa1478c01.png)

**Comment by starkguerraj** [comment]
That sounds like a better sorting option than the epoch as well as providing a better look and taking up less visible space.

My knee jerk reaction doesn't like the removal of the Timestamp and thinks it should remain but I don't really have a good argument for keeping it, especially since it wasn't granular enough to be super useful.

The current option sounds good, maybe in the future, as you said, if its easy enough to figure out a formula field to show a more granular/useful timestamp it could be added in or at least an option to add custom to the layout.

**Comment by jongpie** [comment]
Sounds good, I'll move forward with these changes for now, but will definitely keep looking into other options long-term for a formula field. 

And regarding the removal of the Timestamp - it seems safe to remove it since the log's compact layout (circled below) shows the "Start Time" field, which is the same value as the first log entry's Timestamp field, so you can still effectively see the same datetime on the screen, it's just not in the "log entries" related list anymore. 

![image](https://user-images.githubusercontent.com/1267157/128438662-14ab014b-c68e-4ef9-ad3b-928bda49a8c2.png)

I'll wrap up the new release soon, but let me know if you have any other feedback!
