### ISSUE TITLE
Selective event listening

### ISSUE THREAD

**Issue by itsikra** [jongpie/NebulaLogger#183]
Hi @jongpie 

The Nebula Logger works very well, and we get great benefit from it, listening remotely using a CometD client.

However, we have encountered an issue and are looking for a solution:

We have an enormous amount of logs in our system. 

 
Problem is, we reach the Salesforce Organization daily limit, and get blocked from the rest of the events, on a daily basis. 

**We were thinking that the ability to control which logs we listen to, would help us prevent this:** 
Regularly listen to critical log events, and in case needed - listen to informative events to track down errors, as salesforce keeps the events in the event bus.

We did take advantage of the LoggingLevel, separating logs into different levels, mainly critical logs(Errors, exceptions, etc.) and informative logs (callouts, queries, etc.)

Selective listening, of course, cannot be achieved by changing log levels, can it? we still need all logs to be created, just listen to some of them, and have the others at hand in case they are needed. 

Can you think of, or are you working on any solution for this? 

We did come up with the idea to create separate events for each log level (i.e. LogEntryEventError__e, LogEntryEventDebug__e etc.), that will be created along with the creation of LogEntryEvent__e. (which means double the events created). 

An expansion of that idea is just to add 2-3 more event types (e.g. LogEntryEventHigh__e, LogEntryEventLow__e etc. ) to represent high/low levels of events, and allow the user to decide which logging levels are mapped as High/Low levels of logs, via the LoggerSettings custom setting.

This way, for example, a user could assign some logging levels (e.g. ERROR, WARN, DEBUG) as HIGH, allowing listening only to these logs regularly, while other logging levels (INFO, FINE etc.) could be assigned to LOW level, and listened to on demand. 

Is that something that can be achieved in your project? 
We'd love to hear your thoughts, ideas, insights, criticism etc. 

Thanks!

**Comment by jongpie** [comment]
Hi @itsikra - I'm really thrilled to hear that you & your team are benefiting from Nebula Logger!

As far as this issue, Salesforce has a pilot program that (I think) will provide the functionality you want called [Platform Event Channels](https://help.salesforce.com/s/articleView?id=release-notes.rn_platform_events_filtering_pilot.htm&type=5&release=232). Channels are a new feature for platform event objects that will let you filter which events a subscriber receives - all of Logger's platform event records would still be created, but you can filter which records you subscribe to. 

I have not used this myself yet, but it seems like a good fit for your use case, without needing to create any additional platform event objects. Given that Salesforce is working on this new feature, I'm not planning to implement anything directly within Nebula Logger to handle it - but definitely let me know if you don't think this feature would meet your needs.

**Comment by jongpie** [comment]
Hey again @itsikra - I was thinking about this idea some more today, and assuming you're using the unlocked package, then your idea of using additional platform event object(s) could be [implemented as a plugin](https://github.com/jongpie/NebulaLogger#beta-feature-custom-plugin-framework-for-log__c-and-logentry__c-objects). Long term, I think [Platform Event Channels](https://help.salesforce.com/s/articleView?id=release-notes.rn_platform_events_filtering_pilot.htm&type=5&release=232) will be the best solution for this, but since it's only in pilot, it doesn't immediately solve your issue (or anyone else with a similar issue). Creating a new (semi-temporary) plugin could be developed to provide the functionality you want, without directly changing the existing logging functionality.

High-level, I think your design of another platform event object makes sense (although I'd probably use just 1 additional platform event object, instead of multiple). Next week, I can put together a small prototype of how it could work as a plugin - if it turns out to be fairly straightforward to build & maintain, I'll also consider releasing it as an official plugin so anyone can use it. I'll share my prototype as soon as I have something ready.

**Comment by jongpie** [comment]
@itsikra I've created a draft pull request, PR #185, as an initial attempt at solving this issue. It includes a plugin for the unlocked package, but I believe you're using the managed package - I'm researching options for making it available for the managed package as well.

The plugin includes its own README - you can [read it here](https://github.com/jongpie/NebulaLogger/tree/feature/filtered-events-plugin/nebula-logger-plugins/Filtered-Log-Entry-Events), it covers details about how it works, but essentially you can configure "filters" using custom metadata, and any `LogEntryEvent__e` records that match the filter are automatically republished as `FilteredLogEntryEvent__e` records.

There's still more work I need to do before merging it, but I'd love to know your thoughts on this approach!

**Comment by jongpie** [comment]
Hi @itsikra, I'm going to close this issue & mark it was "won't fix" - the Spring '22 release [provides beta-level support for filtering platform events](https://help.salesforce.com/s/articleView?id=release-notes.rn_platform_events_filtering_beta.htm&type=5&release=236), so this can now be handled directly by the platform, instead of needing to handle this with a custom solution.
