### ISSUE TITLE
Null Record causes error

### ISSUE THREAD

**Issue by vr8hub** [jongpie/NebulaLogger#198]
After getting everything setup (thanks again!), I quickly ran into my first challenge. I have a Get Records, and immediately after it, I put a Add Log SObject action to log the results. But, the flow died with the action complaining it didn't get a required parameter: records.

Except I _did_ specify the parameter, it's just the results of the Get Records was nothing found, so the variable itself was empty, which is precisely what I wanted to log.

The absence of a parameter vs. the parameter being present and empty are two different things. Maybe Apex can't tell the difference in this circumstance(?), but if it can, it would be preferable if the action just logged the fact that the record was empty. I know I can put log actions on both sides of a test following the Get Records, but it would be better (cleaner) if that wasn't necessary.

Thanks!

**Comment by vr8hub** [comment]
Actually, looking at it again, it doesn't matter whether Apex can tell the difference, does it? The field is required on the Flow side, so we can't save the action without specifying a record parameter. So Apex _knows_ that a variable is there. If the variable is NULL, then it should just put an empty string (or NULL or whatever) in the record field.

**Comment by jongpie** [comment]
Hey again @vr8hub! That is actually related to some strange behavior in Flow itself - the Get Records action in Flow sends null as the parameter if no matching records are found. This is different behavior from how Apex works - in Apex, a query with no results returns an empty list (instead of null), so it's a slightly frustrating inconsistency in Flow vs Apex.

But the good news is that it should be an easy fix - I'm going to make the Collection parameter optional for the action "Add Log Entry for SObject Collection", which will prevent this error from happening. I'll let you know as soon as I have this issue resolved, I should have a fix ready over the weekend or early next week.

**Comment by vr8hub** [comment]
Awesome, thanks, Jonathan! (Same for the Record action, please.)

**Comment by jongpie** [comment]
Yeah, great point - I'll make the same change for the Record action as well.
