### ISSUE TITLE
Site Guest User no longer creating logs

### ISSUE THREAD

**Issue by solo-1234** [jongpie/NebulaLogger#219]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

not listed in Installed Packages

### New Bug Summary

Does it make sense that since the Winter 22 release, actions taken by a site guest user no longer cause logs to be created?
I'm fairly certain that it used to create the logs. I just added Read and Create object perms for Log and it didn't help but I probably need to do all the child objects if that's the issue. Just wondering if this is a known issue?

My use case is: Site Guest User creates a record. A trigger then runs on the record and calls a class which does some things and logs some things. I don't see the logs unless the record is created by an internal user.

Thanks!

**Comment by jongpie** [comment]
Reopening this issue - it seems like the solution implemented in `v4.6.9` no longer works in orgs on Spring '22 or Summer '22 releases. 

- When originally implemented, I (foolishly??) [used a hardcoded String 'Guest User License'](https://github.com/jongpie/NebulaLogger/blob/05c4c784a0c20dd032355492dceb8dd9410a69c3/nebula-logger/main/log-management/classes/LogEntryEventHandler.cls#L68), which seemed to work, for a while....
- Now, the license key name appears to use the value 'PID_Guest_User` - this script can be used to retrieve the license key name
  ```java
  for (User user : [SELECT Id, Name, Profile.Name, Profile.UserLicenseId, Profile.UserLicense.LicenseDefinitionKey FROM User
  WHERE Profile.UserLicense.LicenseDefinitionKey LIKE '%Guest%']) {
      System.debug('License name for User ' + user.Name + ': ' + user.Profile.UserLicense.LicenseDefinitionKey);
  }
  ``` 

Ideally, any use of a hardcoded String should be eliminated, but I'll have to do some digging to figure out what other options there are for determining if a User is a Guest Site User

**Comment by jongpie** [comment]
@solo-1234 a quick update on this - I was mistaken on my previous analysis, it does not look like the `LicenseDefinitionKey` value has changed within the platform, I was simply looking at the wrong fields in part of the code. So, I'm not 100% sure why you started seeing this issue again; I'm still going to slightly change the approach being used in the code to determine if the user is a Guest User because I found a somewhat cleaner way to approach it, but I'm not positive that it will solve your issue. Once the new `v4.7.3` release is officially out, I'll let you know and hopefully you can install/test it out.

**Comment by solo-1234** [comment]
Thanks for the update! I'll stay tuned...

**Comment by jongpie** [comment]
@solo-1234 I've just finished releasing [v4.7.3](https://github.com/jongpie/NebulaLogger/releases/tag/v4.7.3), which has a few small changes that I'm hoping help with this issue. If you still encounter any issues, let me know and we can try to get to the bottom of this problem.

**Comment by solo-1234** [comment]
All fixed now, thanks for your help!
