### ISSUE TITLE
LoggerSettingsController_Tests Test Failures

### ISSUE THREAD

**Issue by starkguerraj** [jongpie/NebulaLogger#257]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.6.14

### New Bug Summary

Getting some test errors when run from the Apex test execution page for LoggerSettingsController_Tests.

Deploying change sets and running the tests does not seem to trigger the failures, only when run from this view.

/lightning/setup/ApexTestQueue/home

![image](https://user-images.githubusercontent.com/72459978/147761463-722d686b-e2a4-43b4-9dfa-44f65bbaf456.png)

![image](https://user-images.githubusercontent.com/72459978/147761554-59d63712-e795-4cb2-9656-511b09db5284.png)

**Comment by starkguerraj** [comment]
The install was for all users.

Sounds good, I had not made any changes to the standard profile after installing the unlocked package.

If you wanted me to check just let me know where I could check that for you and I can confirm, my schema settings have restrict access to metadata types enabled and the customize application setting on the profile is disabled.

Alternatively if you plan to move them for the reasons above that will resolve the issue.

**Comment by jongpie** [comment]
@starkguerraj thanks for confirming! I was able to reproduce the issue in a scratch org by installing it for all users - I think this will be an ongoing issue in any org that uses that option, so I think moving these tests to be outside of the package is probably best. It shouldn't cause any major issues with code coverage, and I'll continue running the tests in the GitHub pipeline to ensure that nothing breaks in the future.

I'll get this fixed in the next release (`v4.6.15`) - I don't have a set data for when it'll be released, but hopefully within the next week or two.

**Comment by starkguerraj** [comment]
Sounds good.

Thanks!

**Comment by jongpie** [comment]
@starkguerraj [v4.6.15](https://github.com/jongpie/NebulaLogger/releases/tag/v4.6.15) has been released, which includes a fix for these test failures. Thanks again!

**Comment by starkguerraj** [comment]
Appreciate it.
