### ISSUE TITLE
Contructor of LogMessage with Database.SaveResult as param

### ISSUE THREAD

**Issue by aranwe** [jongpie/NebulaLogger#342]
### New Feature Summary

Just an Idea: add constructor of LogMessage that would accept Database.SaveResult and interate through errors and build some reasonable output.

Right now I have a Helper method for this, but it might be good idea to have this as part of the LogMessage constructor for convenience.

What do you think?

**Comment by jongpie** [comment]
Hi @aranwe - I'm not currently planning to add any new constructors in `LogMessage`, but you could create your own custom class to do this by extending `LogMessage` (it's a virtual class). Here's an example class that uses `List<Database.SaveResult>`:

```java
public without sharing class DatabaseLogMessage extends LogMessage {
    private List<Database.SaveResult> saveResults;

    public DatabaseLogMessage(List<Database.SaveResult> saveResults) {
        super();
        this.saveResults = saveResults;
    }

    public override String getMessage() {
        List<String> saveResultFormattedPieces = new List<String>();
        for (Database.SaveResult saveResult : this.saveResults) {
            if (saveResult.isSuccess() == false) {
                // This is just a basic way to convert the errors to a string, you could do something more elaborate & nicer looking
                saveResultFormattedPieces.add(String.valueOf(saveResult.getErrors()));
            }
        }
        return String.join(saveResultFormattedPieces, '\n');
    }
}
```

Since the example class `DatabaseLogMessage` extends `LogMessage`, you can then pass is as a parameter to any method that uses `LogMessage`:

```java
List<Database.SaveResult> saveResults = Database.insert(new List<Account>{new Account()}, false);
Logger.info(new DatabaseLogMessage(saveResults));
Logger.saveLog();
```

This will then create a `LogEntry__c` record, using whatever format you specify in your own class that extends `LogMessage`. Let me know if this would work for your use case.

![image](https://user-images.githubusercontent.com/1267157/183547839-36d57304-2a78-4218-884c-1c58ef0644e9.png)

**Comment by aranwe** [comment]
@jongpie Works absolutely fine, didn't realize(check) that the class/getMessage was virtual :) 
This is definitely better and way cleaner solution.

Thank you for the great work on the whole NebulaLogger! :)

**Comment by jongpie** [comment]
@aranwe glad to hear that this approach would work for you! If you need anything else, just let me know
