### ISSUE TITLE
LogManagementDataSelector_Tests.it_returns_profiles_for_specified_profile_ids unit test method is failing when some of user profile names begin with lower-case letter

### ISSUE THREAD

**Issue by mykhaylo-partyka** [jongpie/NebulaLogger#393]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.8.3

### New Bug Summary

`LogManagementDataSelector_Tests.it_returns_profiles_for_specified_profile_ids` unit test method is failing when some of user profile names begin with lower-case letter. 
E.g.:  The test will fail if there are three profiles named 'A', 'b', and 'C'.

This is because `SOQL ORDER BY` sorting is case-insensitive, and `List.sort()` method - is case-sensitive.

A solution is to sort both the expected and the returned lists in the same way.

**Comment by jongpie** [comment]
Hi @mykhaylo-partyka thanks for reporting this! I'm not sure why I included the call for `List.sort()` in the test method - [the query in the test method already sorts on name](https://github.com/jongpie/NebulaLogger/blob/v4.8.3/nebula-logger/core/tests/log-management/classes/LogManagementDataSelector_Tests.cls#L158), so `List.sort()` is conceptually redundant, and in practice apparently breaks the test 😭 . I'll remove that extra usage of `List.sort()`, it should be fixed in the next release v4.8.4 (PR #394)
