### ISSUE TITLE
Encountered duplicates in unpackaged/lwc/logger/logger.js-meta.xml: unpackaged/lwc/logger/logger.js.

### ISSUE THREAD

**Issue by Mr-Jree** [jongpie/NebulaLogger#492]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.7

### New Bug Summary

When deploying metadata changes including LWC on tools like Gearset, we encounter this error: 

Encountered duplicates in unpackaged/lwc/logger/logger.js-meta.xml: unpackaged/lwc/logger/logger.js.

**Comment by jongpie** [comment]
Hi @Mr-Jree - I'm not very familiar with Gearset (I've only briefly used it), but my guess is that this issue is caused by something on their side, I don't think it's something specific to Nebula Logger. When this error happens, are you deploying the source code for Nebula Logger? Or are you using Gearset to install the unlocked package?

**Comment by jongpie** [comment]
I'm closing this out since I haven't been able to reproduce and it sounds like an issue with Gearset. If it's still happening & there's anything I can do to help, just let me know & we can reopen this issue if needed.
