### ISSUE TITLE
Ability to Log against RestRequest/RestResponse

### ISSUE THREAD

**Issue by diegocomi** [jongpie/NebulaLogger#514]
### New Feature Summary

Nebula Logger is currently able to log `HttpRequest` and `HttpResponse` against Logs via instance methods on `LogEntryEventBuilder`. 

We have encountered a use case where we want to log failed requests to our own APEX Rest Services - I would like to add the ability to log details of a `RestRequest` in a similar fashion.

In my mind, this would include:
- a new method `global LogEntryEventBuilder setRestRequestDetails(System.RestRequest request)
- new fields on `LogEntry__c`  to store the details
- a dynamic section on the Log Entry lightning page to show these fields if a RestRequest is logged
- modifications to LogEntry event definition and event trigger handler

Happy to be the one working on this if I'm not the only one to find it useful!

**Comment by jongpie** [comment]
@diegocomi this sounds like a great idea to me! If you're interested in working on this one, I'd be happy to review it once it's ready. Just a few additional changes that I think should be included:

1. The new fields on `LogEntry__c` should also be added to the page layout (in addition to the lightning page) - there are still some orgs using Salesforce classic, so I try to keep the page layout updated as well
2. The permission sets `LoggerAdmin` and `LoggerLogViewer` should both have read access to the new `LogEntry__c` fields

Long term, I think it also makes sense to implement these same changes [for the `RestResponse` class](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_restresponse.htm). If you feel like including that as well, great - otherwise, I can add it in a future release.

**Comment by PetitPandaRoux** [comment]
Hello here,

First, a very well done Package done ! I'am using a lot and thanks for it ! I have the same needs concerning the RestRessource and I would like to do the PR on it if Diego is not working on it.

**Comment by diegocomi** [comment]
Hi @PetitPandaRoux  - yes, I have been having some personal issues so I'd be very grateful if you could pick it up

**Comment by jongpie** [comment]
@PetitPandaRoux, thanks for offering to contribute! I've assigned the issue to you, just let me know if you have any questions or run into any issues while working on the PR. One thing you can ignore [in my previous comment (bullet point 1)](https://github.com/jongpie/NebulaLogger/issues/514#issuecomment-1610625964) - I don't think you need to add any new fields to the page layouts, I think just adding the new fields to the `FlexiPage` (lighting app builder pages) is fine. I am planning to deprecate the page layouts in the near future, and I'll only be maintaining the `FlexiPage` metadata going forward, so I don't think you need to worry about the (soon to be deprecated) page layout.

@diegocomi, so sorry to hear that you're having some personal issues - I hope that everything is ok! I'll work with @PetitPandaRoux to get this feature added.

**Comment by Damecek** [comment]
Hello guys is there any progress on this one?

**Comment by jongpie** [comment]
@diegocomi, @PetitPandaRoux, and @Damecek, I had some free time today and decided to work on this enhancement. My changes are in PR #613 - I'm still finalizing some testing & confirming field lengths for a few new fields, but I think I'm nearly done with it. I'm hoping to have this released sometime this week 🥳
