### ISSUE TITLE
Missing FLS from Logger: End User permission set

### ISSUE THREAD

**Issue by n4arora** [jongpie/NebulaLogger#519]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.10.1

### New Bug Summary

FLS of the following fields is missing from the _Logger: End User_ permission set.
Only _Logger: Admin_ and _Logger: Log Viewer_ permission sets have access to all the fields and we don't want to give that level of access to end users.

1. Apex Class
2. Apex Class API Version
3. Apex Class Created Date
4. Apex Class ID
5. Apex Class Last Modified Date
6. Apex Inner Class
7. Apex Method
8. Database Result JSON
9. Exception Stack Trace
10. Has Inline Tags
11. HTTP Request Body
12. HTTP Request Body Masked
13. HTTP Request Compressed
14. HTTP Request Endpoint
15. HTTP Request Method
16. HTTP Response Body
17. HTTP Response Body Masked
18. HTTP Response Header Keys
19. HTTP Response Status
20. HTTP Response Status Code
21. Stack Trace
22. Tags

**Comment by jongpie** [comment]
Hi @n4arora - at the moment, those fields have been intentionally excluded from the _Logger: End User_ permission set. The original goal of this permission set was to provide certain users with limited access to some logging data, and since users don't typically have direct insight into backend information like HTTP requests/responses or Apex classes, I haven't added FLS for these fields. 

I'm hesitant to add these fields to this permission set, as it would expose metadata & integration data, and there are some existing orgs that prefer to not have these fields exposed to end users - by adding these fields to the perm set, it would effectively have the same FLS as the permission set _Logger: Log Viewer_. But I'd love to hear more about your use case - I only know of a small number of orgs that actively use the perm set `Logger: End User`.

**Comment by jongpie** [comment]
I'm closing this out for now, but let me know know if you can provide more information on this request.
