### ISSUE TITLE
Log Entry Detail not created using SYNCHRONOUS_DML

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#526]
### Discussed in https://github.com/jongpie/NebulaLogger/discussions/511

<div type='discussions-op-text'>

<sup>Originally posted by **cbcruz74** June 14, 2023</sup>
Hi, we could not get the Log Entry Tag records to be created using SYNCHRONOUS_DML. Log and Log Entry are being created as expected.
The Log Entry Tag records are created with EVENT_BUS only.

Is this working as designed?</div>

**Comment by JMercie** [comment]
Hey @jongpie, I think I found the problem
<img width="822" alt="image" src="https://github.com/jongpie/NebulaLogger/assets/53920455/e99a484b-f835-4373-8025-2f5cdffd6b0c">

When the operation save method is SYNCHRONOUS_DML, the logEntryEvent does not have a UUID, so the else statement never gets executed. Because of this, "this.tagNames" is always empty when the transaction evaluates "upsertLogEntryTags()" method.

<img width="1215" alt="image" src="https://github.com/jongpie/NebulaLogger/assets/53920455/909dbc55-9ae7-4f97-bbd6-adb0fc46fd29">

The solution may be finding another unique identifier for the map, so when we want to reference it with a .get(), we can assign the value unequivocally to the tag record.
