### ISSUE TITLE
Log headers from HttpResponse (and possibly HttpRequest) objects

### ISSUE THREAD

**Issue by TrangOul** [jongpie/NebulaLogger#561]
### New Feature Summary

This is an expansion of #240.
Currently the logger logs only header keys for `HttpResponse`, but not their values.
Please consider logging both header keys and values. They could be logged in a simple `Header: value` format (so it matches the [HTTP standard](https://datatracker.ietf.org/doc/html/rfc1945#section-4.2)), and delimited by new lines, just like the keys in the current logger. Retrieving the values requires only calling [`getHeader(key)`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_http_httpresponse.htm#apex_System_HttpResponse_getHeader) method.

Current code (`LogEntryEventBuilder.cls`):
```
this.logEntryEvent.HttpResponseHeaderKeys__c = String.join(response.getHeaderKeys(), NEW_LINE_DELIMITER);
```

New code:
```
private static final String HTTP_HEADER_FORMAT = '{0}: {1}';

(...)

List<String> headers = new List<String>();
for (String key : response.getHeaderKeys()) {
	headers.add(String.format(HTTP_HEADER_FORMAT, new List<String>{key, response.getHeader(key)}));
}
this.logEntryEvent.HttpResponseHeaders__c = String.join(response.getHeaderKeys(), NEW_LINE_DELIMITER);
```
`LogEntryEvent__e.HttpResponseHeaderKeys__c` and `LogEntry__c.HttpResponseHeaderKeys__c` fields would need to be renamed, as after this change not only keys would be logged.

The same could be done with `HttpRequest`, but it'd be tricky, as the current API do not provide `getHeaders()` method.

**Comment by jongpie** [comment]
@TrangOul this sounds good to me! Thanks so much for providing the code snippet & docs for the HTTP standard, it's very helpful context for me to have.

For now, I'll only implement this for `HttpResponse` since there's not a way to get the headers for `HttpRequest`. Long-term, I'll see if there's a way to make this work for `HttpRequest` as well, but I'll do an initial release for just `HttpResponse`.

I'm going to leave the existing fields `LogEntryEvent__e.HttpResponseHeaderKeys__c` and `LogEntry__c.HttpResponseHeaderKeys__c` & continue populating them with only the keys - there's no way to do a true field rename, and I know of some orgs are already using the existing field `LogEntry__c.HttpResponseHeaderKeys__c` for some automation. I'll instead add new fields to store the key-value pair (in addition to the existing fields that store only the keys).

**Comment by jongpie** [comment]
@TrangOul I've created a PR for this - PR #564. I'm still working on a few details, but I'm hoping to finish it sometime this week.

**Comment by TrangOul** [comment]
Oh, I didn't expect such a quick response. Thank you!

**Comment by jongpie** [comment]
@TrangOul luckily, I had some free time yesterday + this was a very easy change for me to make (especially since you provided a very helpful Apex code snippet), so I thought I'd get this released ASAP 🥳 

And that sounds great - I'll move forward with just `HttpResponse` for now. If/when there's a solution for `HttpResponse`, I can add it in a future release.

**Comment by jongpie** [comment]
@TrangOul I've just finished releasing this [as `v4.11.8](https://github.com/jongpie/NebulaLogger/releases/tag/v4.11.8) 🥳 Whenever you have a chance to try it out, let me know if you run into any issues. 

Thanks again for the suggestion & all of your help!

**Comment by TrangOul** [comment]
Thank you for quick development! Let me install the new version on my sandbox and perform some smoke tests.
If I find any issue (hopefully not), I will let you know. Thanks again!

**Comment by TrangOul** [comment]
After some initial tests everything seems to look okay. Response headers are logged with their values.

The only thing I can complain about is that now there are two long text fields in the Log layout: HTTP Response Header Keys
 and HTTP Response Headers, with the latter duplicating the information from the former.

Is it possible to show only one of them, conditionally, depending on the flag `StoreHttpResponseHeaderValues`?
