### ISSUE TITLE
Setup test coverage in Code Climate

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#58]

**Comment by jamessimone** [comment]
What about migrating to the use of codecov?

**Comment by jongpie** [comment]
@jamessimone I love the idea, CodeCov seems like the better option now - I hadn't really seen CodeCov when I originally made this issue, but I think it's been really helpful on your rollup repo

**Comment by jamessimone** [comment]
@jongpie I'd do this one myself but you have to be the one to auth Github to your account, as well as installing the app: https://github.com/apps/codecov - doesn't seem I have the permissions to do so. 

After that, it looks like you'll need to slightly tweak your Github Action to separate the deploy and testing parts, because `sfdx force:source:deploy` doesn't expose the options necessary when running tests to save them (the `-c -d tests/apex -r human` arguments that you can supply to `force:apex:test:run` are the ones that the default Github Action for codecov expects (in addition to whatever `-w` interval is best).

**Comment by jongpie** [comment]
Awesome, thanks for the details - sounds like I'll need to finally start using scratch orgs too, I'll see if I can make some progress on it this week.

**Comment by jamessimone** [comment]
Ah yeah, for the code coverage to be calculated correctly - that or a totally siloed sandbox!

**Comment by jongpie** [comment]
Closed in #126
