### ISSUE TITLE
Add the Tag to the Error record while writing to LogEntry__c Object

### ISSUE THREAD

**Issue by sarat-vs** [jongpie/NebulaLogger#580]
Hello @jongpie ,

Good day!

I am trying to add a tag to the record while inserting into LogEntry__c Object. My requirement is that 'Tags__c' field of the Object LogEntry__c should be filled with some custom String while inserting the the LogEntry__c record. Currently I use the below snippet to create the LogEntry__c record:

**try{
} catch(Exception ex){
  Logger.error('Error on class: +ex);
  Logger.error('Method: methodname()').parseStackTrace(ex.getStackTraceString());
  Logger.saveLog();
}**

I would like to go with the Apex approach here. Can you please let me know what extra code/snippet I should use with the above in order to get the Tag__c field also get filled. I am using the unlocked package (Version : 4.9.11)

Thanks in advance.

**Comment by jongpie** [comment]
Hi @sarat-vs - any time you use one of the logging methods, like `Logger.error()`, the method returns an instance of the class `LogEntryEventBuilder`. The builder class provides some additional methods to further customize each entry - and in the case of tagging, you can call either `addTag(String)` or `addTags(List<String>)`. There's some additional info about tagging available [in the README](https://github.com/jongpie/NebulaLogger/tree/v4.11.12#adding-tags-in-apex). 

- One detail to note: by default, tags are stored in the custom objects `LoggerTag__c` and `LogEntryTag__c`. If you would rather store them in the field `LogEntry__c.Tag__c`, you can update the `LoggerParameter__mdt` record `NormalizeTagData` from `true` to `false`

And looking at your sample code, I think you can simplify some of it 
- If you pass your exception as a second parameter (instead of combining it with the string method), then Nebula Logger will automatically track more details about the exception on the corresponding `LogEntry__c` object
- You don't have to call `parseStackTrace()` yourself, Nebula Logger will automatically do that for you
- You don't need to hardcode your method name as a string (referring to 'Method: methodname()' in your code), Nebula Logger will automatically track the method name for you

You can simplify & add tagging to your code like this:

```apex
try{
} catch(Exception ex){
  Logger.error('Unexpected error occurred', ex).addTag('some tag');
  Logger.saveLog();
}
```

With the approach above, it will save the logging data, but it won't throw the exception. If you'd like it to automatically save & throw the exception, you can use the method `Logger.exception()`:

```apex
try{
} catch(Exception ex){
  Logger.exception('Unexpected error occurred', ex).addTag('some tag');
}
```

Hope this helps! Let me know if you have any other questions.

**Comment by jongpie** [comment]
I'm closing this out since this is more of a question/discussion instead of an actual issue. Let me know if you have any follow up questions.
