### ISSUE TITLE
Long data upserts should not throw Value too long for field error

### ISSUE THREAD

**Issue by Damecek** [jongpie/NebulaLogger#592]
### New Feature Summary

It would be better in this case where we receive a email message with content `Value too long for field`, to truncate the inserted value? We could use a `truncateFieldValue` method on all Log and LogEntry fields. Further more we could update the method to leverage a `''.abbreviate()` which adds `...` at the end of the string in case it was longer than the defined length.

**Comment by Damecek** [comment]
related to this [issue](https://github.com/jongpie/NebulaLogger/issues/590)

**Comment by jongpie** [comment]
@Damecek this has been implemented [in the new release `v4.12.6`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.6) 🥳 . I've updated the class `LoggerDataStore.EventBus` to automatically truncate String field values any time Nebula publishes platform events. I also used your suggestion to use `String.abbreviate()` (instead of `String.left()`) so it includes the `...` at the end.
