### ISSUE TITLE
While Running APEX tests, Logs and Log_entries don't appear to being written

### ISSUE THREAD

**Issue by stephenpstanley** [jongpie/NebulaLogger#654]
### Package Edition of Nebula Logger

Managed Package

### Package Version of Nebula Logger

4.11

### New Bug Summary

I'm using Nebula Logger to write a log entry from a Future method so that authentication failures for callouts to a SOAP web service can be identified. I originally wondered if maybe the EVENT_BUS save method might be the problem even though the callout is being done before a Test.StopTest() call which should publish all events, so when in test mode, I'm using SYNCHRONOUS_DML

The code being tested is:
// make sure that logs are published using the event bus unless in test and set the scenario
            If (!Test.isRunningTest()){
                Nebula.Logger.setSaveMethod(Nebula.Logger.SaveMethod.EVENT_BUS);
                system.debug('Not running a test - set to Event Bus save');
            } else {
                Nebula.Logger.setSaveMethod(Nebula.Logger.SaveMethod.SYNCHRONOUS_DML);
                **system.debug('Running a test - set to Synchronous DML save');**
            }
            Nebula.Logger.setScenario('Weighbridge Ticket Callout');
            Nebula.Logger.error('Authentication failed for weighbridge site: ' + siteNumber +
            '\n\nFull response from the callout was:\n' + res.GetBody());
            Nebula.Logger.SaveLog();
            **System.debug('Error logged for site: ' + siteNumber );**

My callout mock returns an authentication failure and the two lines in bold are logged in the debug log so the failure is being detected, but my test assertion (see below) fails as there are no Nebula__Log__c records at all

        //Check to see if a log record has been written 
        List<Nebula__Log__c> logs = [SELECT ID FROM Nebula__Log__c];
        System.AssertEquals(1,logs.size(),'Was expecting 1 log record');

The debug log includes savelog entries

I see mention of a CMDT setting in one of your issues where you can configure whether or not testing generates log entries, but I can't see a logger parameter entry that might to set this flag in my org.  I have only got the CMDT records that are installed by the managed packed and all the booleans are set to true

Can you see what I'm doing wrong or is there a bug?

**Comment by jongpie** [comment]
Hi @stephenpstanley - I think that the issue is because you're trying to use `SYNCHRONOUS_DML` as the save method. There's currently an open issue, #457, to resolve this bug - see [my comment in this discussion](https://github.com/jongpie/NebulaLogger/discussions/454#discussioncomment-5094326) for more context. I am hoping to finally address that issue in the coming months, but in the meantime, you should be able to use `EVENT_BUS` instead. 

If you still don't see the `Nebula__Log__c` records being created when using `EVENT_BUS`, try including `Test.getEventBus().deliver()` in your test method to force the platform events to be published.

Let me know if this works for you!

**Comment by stephenpstanley** [comment]
Perfect.  Thank you.  Issue closed

**Comment by jongpie** [comment]
No problem - please let me know if you run tino any other issues!
