### ISSUE TITLE
It seems my sandbox and production both stopped inserting log entries on 2/6/24

### ISSUE THREAD

**Issue by tomtam-c2fo** [jongpie/NebulaLogger#658]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.13.4

### New Bug Summary

My sandbox and production both stopped inserting log entries on 2/6/24. I updated my sandbox package to v4.13.4 today, prod is still on v4.12.9. Tried running execute anonymous but still won't insert a log or cannot see log entry in All list view.

**Comment by jongpie** [comment]
Hi @tomtam-c2fo - since this is happening in 2 different orgs, using 2 different versions of Nebula Logger, I'm wondering if it's possibly related to the `LoggerSettings__c` records in your orgs. Could you run this anonymous Apex script, and share the JSON results from the debug log? This should provide enough details to know if the `LoggerSettings__c` data is the source of the problem.

```apex
System.debug(
  JSON.serializePretty(
    [
      SELECT
        DefaultSaveMethod__c,
        DefaultPlatformEventStorageLocation__c,
        DefaultPlatformEventStorageLoggingLevel__c,
        DefaultScenario__c,
        EndTime__c,
        IsApexSystemDebugLoggingEnabled__c,
        IsEnabled__c,
        LoggingLevel__c,
        SetupOwner.Type,
        SetupOwnerId,
        StartTime__c
      FROM LoggerSettings__c
    ]
  )
);
```

**Comment by tomtam-c2fo** [comment]
Hi there, thanks for getting back to me. So I navigated to the Custom setting page in both orgs (different versions). On view the Platform Event Storage Location field appears blank. When I click edit, it auto fills with CUSTOM_OBJECTS. After clicking  Save, I retried execute anonymous. Works for both orgs. 

/

**Comment by jongpie** [comment]
@tomtam-c2fo glad to hear you were able to sort it out! If you need anything else, please let me know.
