### ISSUE TITLE
Issue during the insertion of Nebula logs

### ISSUE THREAD

**Issue by nikhilguptamc** [jongpie/NebulaLogger#707]
### Package Edition of Nebula Logger

Managed Package

### Package Version of Nebula Logger

v4.13

### New Bug Summary

We have a logic which is worked during v4.6. But after upgrading to latest version v4.13, we were facing below issues
- System.LimitException: Nebula:Too many Publish Immediate DML: 151
- System.LimitException: Apex CPU time limit exceeded(javascript:void(0);)
Below are the existing configurations tried
<img width="673" alt="image" src="https://github.com/jongpie/NebulaLogger/assets/103033095/9c70b67a-21c4-4344-9ecc-4a00ca98cb3b">
<img width="665" alt="image" src="https://github.com/jongpie/NebulaLogger/assets/103033095/bd3d7e83-b784-454d-918f-1ca9161be73f">
<img width="400" alt="image" src="https://github.com/jongpie/NebulaLogger/assets/103033095/3a61c4a8-9faa-472e-8afd-f89f8ca19bd4">

Please help us in configuring Logger Settings and resolving the issue. Thanks!

**Comment by jongpie** [comment]
Hi @nikhilguptamc - based on your screenshots, I don't see any issues with your setup. Since you've upgraded from `v4.6` to `v4.13`, it's possible that some newer features are using more CPU time - but the error `Too many Publish Immediate DML: 151` would have to be something from your side, Nebula Logger doesn't automatically save for you, so something in your Apex code/Flows is probably calling `saveLog()` too many times (which could also be related to the CPU limit errors). Can you check if you have anything running in a `for` loop when this error occurs?
